### ISSUE TITLE
A fatal error has been detected by the Java Runtime Environment

### ISSUE THREAD

**Issue by litronics** [nibi79/worxlandroid#85]
Openhab environment running on Docker:
```
runtimeInfo:
  version: 3.4.0.M4
  buildString: Milestone Build
locale: de-DE
systemInfo:
  configFolder: /openhab/conf
  userdataFolder: /openhab/userdata
  logFolder: /openhab/userdata/logs
  javaVersion: 11.0.17
  javaVendor: Alpine
  osName: Linux
  osVersion: 5.15.84-v8+
  osArchitecture: aarch64
  availableProcessors: 4
  freeMemory: 181065800
  totalMemory: 328204288
  startLevel: 100
```

Installed v3.4.1-beta 2023-04-09 and the container keeps restarting with a fatal JRE Error.
Here the full dump of the Errormessage:
[hs_err_pid27.log](https://github.com/nibi79/worxlandroid/files/11523772/hs_err_pid27.log)
